In [3]:
import imageio
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

In [20]:
def comp_2d(image_2d,mean_mat):
    #print(image_2d)
    cov_m = image_2d - mean_mat #np.mean(image_2d,axis = 0)
    #print(cov_m)
    eig_val,eig_vec = np.linalg.eig(np.cov(cov_m))
    
    idx = np.argsort(eig_val)
    idx = idx[::-1]
    eig_vec = eig_vec[:,idx]
    eig_val = eig_val[idx]
    
    #选取特征值个数
    eig_val_sum = np.sum(eig_val)
    r = np.linalg.matrix_rank(image_2d)
    p_eig = 0
    for i in range(r):
        p_eig = p_eig + eig_val[i]
        if p_eig > 0.99*eig_val_sum :
            break
    n_pick = i
    eig_vec =eig_vec[:,range(n_pick)]
    
    #计算压缩率
    score = np.dot(eig_vec.T,cov_m)
    #计算重构误差
    recon = np.dot(eig_vec,score) + mean_mat#+ np.mean(image_2d,axis = 0).T
    recon_img_mat = np.uint8(np.absolute(recon))
    
    compress = np.size(eig_vec)+ np.size(score)#+np.size(np.mean())
    origin_img = np.size(image_2d) 
    error = np.linalg.norm(recon_img_mat-image_2d)
    return recon_img_mat,compress,origin_img,error

    
    
    
    

In [30]:
a = imageio.imread("airplane/airplane01.tif")
a_np = np.array(a)
a_r = a_np[:,:,0]
print(a_r/100)
a_g = a_np[:,:,1]
a_b = a_np[:,:,2]
#a_r_recon,a_g_recon,a_b_recon = comp_2d(a_r),comp_2d(a_g),comp_2d(a_b)
#recon_img = np.dstack((a_r_recon,a_g_recon,a_b_recon))
#recon_img = Image.fromarray(recon_img)
#recon_img.show()


[[1.15 1.21 1.25 ... 1.09 1.1  1.17]
 [1.16 1.2  1.23 ... 1.07 1.09 1.19]
 [1.18 1.21 1.24 ... 1.1  1.11 1.13]
 ...
 [1.67 1.74 1.83 ... 1.82 1.81 1.79]
 [1.74 1.8  1.83 ... 1.79 1.8  1.81]
 [1.74 1.78 1.81 ... 1.81 1.82 1.83]]
[[2.46 2.53 2.58 ... 2.25 2.27 2.41]
 [2.47 2.5  2.53 ... 2.21 2.25 2.45]
 [2.49 2.51 2.52 ... 2.27 2.29 2.33]
 ...
 [3.5  3.64 3.82 ... 3.83 3.81 3.77]
 [3.64 3.76 3.82 ... 3.77 3.79 3.81]
 [3.64 3.72 3.78 ... 3.81 3.83 3.85]]


In [22]:
img_list_r = []
img_list_r_mean = 0
img_list_g = []
img_list_g_mean = 0
img_list_b = []
img_list_b_mean = 0
for i in range(100):
    if i > 9:
        str_tmp = 'agricultural/agricultural' +str(i)+'.tif'
    else:
        str_tmp = 'agricultural/agricultural0' +str(i)+'.tif'
    b = imageio.imread(str_tmp)
    b_array = np.array(b)
    print(b_array.shape)
    img_list_r.append(b_array[:,:,0])
    img_list_g.append(b_array[:,:,1])
    img_list_b.append(b_array[:,:,2])
    img_list_r_mean = img_list_r_mean + b_array[:,:,0]/100
    img_list_g_mean = img_list_g_mean + b_array[:,:,1]/100
    img_list_b_mean = img_list_b_mean + b_array[:,:,2]/100
total_compress = 0
total_origin = 0
total_error = 0
for j in range(100):
    a_r_recon,r_compress,r_origin,r_error = comp_2d(img_list_r[j],img_list_r_mean)
    a_g_recon,g_compress,g_origin,g_error = comp_2d(img_list_g[j],img_list_r_mean)
    a_b_recon,b_compress,b_origin,b_error = comp_2d(img_list_b[j],img_list_r_mean)
    total_compress += r_compress + g_compress + b_compress
    total_origin += r_origin + g_origin+ b_origin
    total_error += r_error + g_error + b_error
    recon_img = np.dstack((a_r_recon,a_g_recon,a_b_recon))
    recon_img = Image.fromarray(recon_img)
    #recon_img.save('agricultural_recon/'+str(j)+'.tif')
print('图片的压缩率为'+str(100*total_compress/total_origin)+'%')
print('图片的平均重构误差为'+str(total_error/100))


(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 

In [15]:
img_list_r = []
img_list_r_mean = 0
img_list_g = []
img_list_g_mean = 0
img_list_b = []
img_list_b_mean = 0
for i in range(100):
    if i > 9:
        str_tmp = 'agricultural/agricultural' +str(i)+'.tif'
    else:
        str_tmp = 'agricultural/agricultural0' +str(i)+'.tif'
    b = imageio.imread(str_tmp)
    b_array = np.array(b)
    print(b_array.shape)
    img_list_r.append(b_array[:,:,0])
    img_list_g.append(b_array[:,:,1])
    img_list_b.append(b_array[:,:,2])
    img_list_r_mean = img_list_r_mean + b_array[:,:,0]/100
    img_list_g_mean = img_list_g_mean + b_array[:,:,1]/100
    img_list_b_mean = img_list_b_mean + b_array[:,:,2]/100
total_compress = 0
total_origin = 0
total_error = 0
for j in range(100):
    a_r_recon,r_compress,r_origin,r_error = comp_2d(img_list_r[j],img_list_r_mean)
    a_g_recon,g_compress,g_origin,g_error = comp_2d(img_list_g[j],img_list_r_mean)
    a_b_recon,b_compress,b_origin,b_error = comp_2d(img_list_b[j],img_list_r_mean)
    total_compress += r_compress + g_compress + b_compress
    total_origin += r_origin + g_origin+ b_origin
    total_error += r_error + g_error + b_error
    recon_img = np.dstack((a_r_recon,a_g_recon,a_b_recon))
    recon_img = Image.fromarray(recon_img)
    recon_img.save('agricultural_recon/'+str(j)+'.tif')
print('图片的压缩率为'+str(100*total_compress/total_origin)+'%')
print('图片的平均重构误差为'+str(total_error/100))


(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 256, 3)
(256, 